name: golangci-lint on macOS

on: [push]

permissions:
  contents: read

# do a separate lint job on macOS to catch platform-dependent problems
jobs:
  golangci:
    name: Lint macOS
    runs-on: macos-latest

    steps:
      - name: Library dependencies
        run: brew install mpv
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Export paths
        uses: spezifisch/export-homebrew-build-paths@v1.0.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
